`$optionsData` param to AddEntity Method, PaymentMethod Facade, `requestId` Added
intuit/QuickBooks-V3-PHP-SDK pull request #313
Opened 2020-05-18 15:18 UTC by PeterCat12

Added a few bits of missing functionality. 

## Changes
- a `$requestId` parameter was added to the following methods of the `\QuickBooksOnline\API\DataService\DataService` class 
    - \QuickBooksOnline\API\DataService\DataService::Update
    - \QuickBooksOnline\API\DataService\DataService::Add
    - \QuickBooksOnline\API\DataService\DataService::Void
- Added the missing `PaymentMethod` Facade
- a `$optionsData` paaameter was added to the `\QuickBooksOnline\API\DataService\Batch::AddEntity` method.

## Issues:
- https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/304
- https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/278

Please let me know if anything clashes with existing style, etc. 

I also see the `optionsData` param being taken care of in `https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/311/files`

2020-05-20 18:25 UTC, bsivalingam commented
@PeterCat12 Thanks for your PR. I will review it.

2020-06-02 14:48 UTC, PeterCat12 commented
Conflicts resolved 👍

2022-01-05 07:26 UTC, julianandreszb requested changes

2022-01-05 07:26 UTC, julianandreszb commented on src/Facades/PaymentMethod.php
> +            throw new \Exception("Target object class:{" .  $classOfObj . "} is not an instance of PaymenMethodt.");
PaymenMethodt -to-> PaymenMethod

2022-02-23 17:48 UTC, DIntriglia commented
Can we get an update on this to get this integrated?

2022-04-17 15:44 UTC, PeterCat12 commented
@DIntriglia I'm not longer working with QB so I don't really have an priority to integrate this in. I recommend taking this code and opening up a new PR with @julianandreszb 's suggested change.

2022-04-17 15:44 UTC, closed without merging

2022-04-18 04:27 UTC, DIntriglia commented
@PeterCat12 Fair enough. I have a fork of this. I will try to implement this change and then PR the fork at a later time. Not sure if this is being maintained so I'll probably stick to using my local repo until I hear an update.

2022-06-28 08:45 UTC, kingIZZZY commented
Temporary / hacky workaround:

```php
$pm = QuickBooksOnline\API\Facades\FacadeHelper::reflectArrayToObject("PaymentMethod", ['Name' => 'Bitcoin', 'Type' => ['value' => 'NON_CREDIT_CARD']], true );
$dataService->add($pm);
```