Update LoggerBase.php
intuit/QuickBooks-V3-PHP-SDK pull request #481
Opened 2023-03-24 15:38 UTC by webkulabhi

In file vendor/quickbooks/v3-php-sdk/src/Core/Configuration/LocalConfigReader.php using undefined following property 
/**
     * @var string
     */
    public $ServiceRequestLoggingLocation;
    
    /**
     * @var string */ public $EnableRequestResponseLogging; on line number 414

public static function setupLogger($ippConfig, $ServiceRequestLoggingLocation, $EnableRequestResponseLogging)
    {
        $ippConfig->Logger = new Logger();
        $ippConfig->Logger->RequestLog->ServiceRequestLoggingLocation = $ServiceRequestLoggingLocation;
        $ippConfig->Logger->RequestLog->EnableRequestResponseLogging = $EnableRequestResponseLogging;
    }

2023-03-24 15:39 UTC, webkulabhi commented
issues : https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/480

2023-04-19 08:22 UTC, ankit-gautam23 requested changes
Why are we not implementing cases for if file exists or not? I can't even see a single try catch block to capture the exceptions and all

2023-07-31 13:13 UTC, algirdasbr commented
This still looks like a valuable improvement. At least it fixes PHP 8.2 deprecation notices about dynamic properties.

2023-08-03 06:25 UTC, sujitharamadass commented
Please try with the latest version 6.1.2

2023-08-03 06:25 UTC, closed without merging